name: Buil

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: set up jdk
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: setup gradle
      uses: gradle/actions/setup-gradle@v4 #  NEW AND OFFICIAL


    - name: give execution priviliges
      run: chmod +x ./mod-1.21.10/gradlew

    - name: compile
      run: ./gradlew build
      working-directory: ./mod-1.21.10

    - name: save artefact
      uses: actions/upload-artifact@v4
      with:
        name: MultiWorldPositions-1.21.11-Jar
        path: mod-1.21.10/build/libs/*.jar
